name: grant
base: core24
version: 'v0.2.1'
summary: Verify licenses in the SBOM
description: |
  Search an SBOM for licenses and the packages they belong to

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  s390x:
    build-for: [s390x]
    build-on: [s390x]
  ppc64el:
    build-for: [ppc64el]
    build-on: [ppc64el]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

grade: stable
confinement: strict

parts:
  grant:
    plugin: go
    source: https://github.com/anchore/grant.git
    source-type: git
    source-tag: 'v0.2.1'
    prime:
      - bin/grant
    build-snaps:
      - go

apps:
  grant:
    command: bin/grant
    plugs:
      - network
      - home
      - removable-media

